version: "3"
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - /docker/:/etc/selenoid/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/selenoid/video/:/opt/selenoid/video/
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video/"]
  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_105.0_vnc:
    image: selenoid/vnc_chrome:105.0
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    network_mode: bridge
  chrome_105.0:
    image: selenoid/chrome:105.0
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    network_mode: bridge