name: Dockerize the test framework and push the Docker image to DockerHub

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Dockerize the web test framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull the project
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: man27/api-framework:latest
