name: Run Amazon Web Tests in GitHub Actions

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choose a browser to run the tests on (Only chrome for now))
        required: true
        options:
          - chrome
  
jobs:
  test:
    name: Amazon Web automated tests
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}
    
    steps:
      - name: Pull the project
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: restore
          
      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v1
        
      - run: chromedriver --url-base=/wd/hub &
          
      - name: Run the Web tests
        run: mvn clean test
        
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        continue-on-error: true
        with:
          step: save
