name: Run Amazon Web Tests in GitHub Actions

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Amazon Web automated tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull the project
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Start Selenoid Server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1
          
      - name: Run the Web tests
        run: mvn clean test
